use events;
use super::ffi;

pub fn keyboardevent_to_event(wparam: ffi::WPARAM, lparam: ffi::LPARAM) -> events::KeyboardEvent {
    let scancode = ((lparam >> 16) & 0xff) as u8;
    let scancode = scancode_to_code(scancode as u16);       // FIXME: value > 0xff never reached
    let vkey = vkeycode_to_element(wparam);

    // TODO: cache this somehow
    let locale = unsafe {
        use libc;
        use std::mem;

        let mut buffer: [libc::wchar_t, ..ffi::KL_NAMELENGTH] = mem::uninitialized();
        if ffi::GetKeyboardLayoutNameW(buffer.as_mut_slice().as_mut_ptr()) == 0 {
            None
        } else {
            String::from_utf16(buffer.as_slice().init())
        }
    };

    events::KeyboardEvent {
        code: scancode,
        key: vkey,
        location: events::StandardLocation,     // FIXME
        locale: locale,
        repeat: false,     // FIXME
        alt_key: false,     // FIXME
        ctrl_key: false,     // FIXME
        meta_key: false,     // FIXME
        shift_key: false,     // FIXME
        is_composing: false,     // FIXME
    }
}

fn scancode_to_code(scancode: u16) -> Option<&'static str> {
    match scancode {
        0x0001 => Some("Escape"),
        0x0002 => Some("Digit0"),
        0x0003 => Some("Digit1"),
        0x0004 => Some("Digit2"),
        0x0005 => Some("Digit3"),
        0x0006 => Some("Digit4"),
        0x0007 => Some("Digit5"),
        0x0008 => Some("Digit6"),
        0x0009 => Some("Digit7"),
        0x000A => Some("Digit8"),
        0x000B => Some("Digit9"),
        0x000C => Some("Minus"),
        0x000D => Some("Equal"),
        0x000E => Some("Backspace"),
        0x000F => Some("Tab"),
        0x0010 => Some("KeyQ"),
        0x0011 => Some("KeyW"),
        0x0012 => Some("KeyE"),
        0x0013 => Some("KeyR"),
        0x0014 => Some("KeyT"),
        0x0015 => Some("KeyY"),
        0x0016 => Some("KeyU"),
        0x0017 => Some("KeyI"),
        0x0018 => Some("KeyO"),
        0x0019 => Some("KeyP"),
        0x001A => Some("BracketLeft"),
        0x001B => Some("BracketRight"),
        0x001C => Some("Enter"),
        0x001D => Some("ControlLeft"),
        0x001E => Some("KeyA"),
        0x001F => Some("KeyS"),
        0x0020 => Some("KeyD"),
        0x0021 => Some("KeyF"),
        0x0022 => Some("KeyG"),
        0x0023 => Some("KeyH"),
        0x0024 => Some("KeyJ"),
        0x0025 => Some("KeyK"),
        0x0026 => Some("KeyL"),
        0x0027 => Some("Semicolon"),
        0x0028 => Some("Quote"),
        0x0029 => Some("Backquote"),
        0x002A => Some("ShiftLeft"),
        0x002B => Some("Backslash"),
        0x002C => Some("KeyZ"),
        0x002D => Some("KeyX"),
        0x002E => Some("KeyC"),
        0x002F => Some("KeyV"),
        0x0030 => Some("KeyB"),
        0x0031 => Some("KeyN"),
        0x0032 => Some("KeyM"),
        0x0033 => Some("Comma"),
        0x0034 => Some("Period"),
        0x0035 => Some("Slash"),
        0x0036 => Some("ShiftRight"),
        0x0037 => Some("NumpadMultiply"),
        0x0038 => Some("AltLeft"),
        0x0039 => Some("Space"),
        0x003A => Some("CapsLock"),
        0x003B => Some("F1"),
        0x003C => Some("F2"),
        0x003D => Some("F3"),
        0x003E => Some("F4"),
        0x003F => Some("F5"),
        0x0040 => Some("F6"),
        0x0041 => Some("F7"),
        0x0042 => Some("F8"),
        0x0043 => Some("F9"),
        0x0044 => Some("F10"),
        0x0045 => Some("Pause"),
        0x0046 => Some("ScrollLock"),
        0x0047 => Some("Numpad7"),
        0x0048 => Some("Numpad8"),
        0x0049 => Some("Numpad9"),
        0x004A => Some("NumpadSubtract"),
        0x004B => Some("Numpad4"),
        0x004C => Some("Numpad5"),
        0x004D => Some("Numpad6"),
        0x004E => Some("NumpadAdd"),
        0x004F => Some("Numpad1"),
        0x0050 => Some("Numpad2"),
        0x0051 => Some("Numpad3"),
        0x0052 => Some("Numpad0"),
        0x0053 => Some("NumpadDecimal"),
        0x0054 => Some("PrintScreen"),
        0x0056 => Some("IntlBackslash"),
        0x0057 => Some("F11"),
        0x0058 => Some("F12"),
        0x0059 => Some("NumpadEqual"),
        0x0064 => Some("F13"),
        0x0065 => Some("F14"),
        0x0066 => Some("F15"),
        0x0067 => Some("F16"),
        0x0068 => Some("F17"),
        0x0069 => Some("F18"),
        0x006A => Some("F19"),
        0x006B => Some("F20"),
        0x006C => Some("F21"),
        0x006D => Some("F22"),
        0x006E => Some("F23"),
        0x0070 => Some("KanaMode"),
        0x0071 => Some("Lang2"),
        0x0072 => Some("Lang1"),
        0x0073 => Some("IntlRo"),
        0x0076 => Some("F24"),
        0x0079 => Some("Convert"),
        0x007B => Some("NonConvert"),
        0x007D => Some("IntlYen"),
        0x007E => Some("NumpadComma"),
        0xE010 => Some("MediaTrackPrevious"),
        0xE019 => Some("MediaTrackNext"),
        0xE01C => Some("NumpadEnter"),
        0xE01D => Some("ControlRight"),
        0xE020 => Some("VolumeMute"),
        0xE021 => Some("LaunchApp2"),
        0xE022 => Some("MediaPlayPause"),
        0xE024 => Some("MediaStop"),
        0xE02E => Some("VolumeDown"),
        0xE030 => Some("VolumeUp"),
        0xE032 => Some("BrowserHome"),
        0xE035 => Some("NumpadDivide"),
        0xE037 => Some("PrintScreen"),
        0xE038 => Some("AltRight"),
        0xE045 => Some("NumLock"),
        0xE046 => Some("Pause"),
        0xE047 => Some("Home"),
        0xE048 => Some("ArrowUp"),
        0xE049 => Some("PageUp"),
        0xE04B => Some("ArrowLeft"),
        0xE04D => Some("ArrowRight"),
        0xE04F => Some("End"),
        0xE050 => Some("ArrowDown"),
        0xE051 => Some("PageDown"),
        0xE052 => Some("Insert"),
        0xE053 => Some("Delete"),
        0xE05B => Some("OSLeft"),
        0xE05C => Some("OSRight"),
        0xE05D => Some("ContextMenu"),
        0xE05E => Some("Power"),
        0xE065 => Some("BrowserSearch"),
        0xE066 => Some("BrowserFavorites"),
        0xE067 => Some("BrowserRefresh"),
        0xE068 => Some("BrowserStop"),
        0xE069 => Some("BrowserForward"),
        0xE06A => Some("BrowserBack"),
        0xE06B => Some("LaunchApp1"),
        0xE06C => Some("LaunchMail"),
        0xE06D => Some("MediaSelect"),
        0xE0F1 => Some("Lang2"),
        0xE0F2 => Some("Lang1"),
        _ => None
    }
}

fn vkeycode_to_element(code: ffi::WPARAM) -> Option<&'static str> {
    // FIXME: all these strings are unchecked
    match code {
        ffi::VK_BACK => Some("Backspace"),
        ffi::VK_TAB => Some("Tab"),
        //ffi::VK_CLEAR => Some("Clear"),
        ffi::VK_RETURN => Some("Enter"),
        //ffi::VK_SHIFT => Some("Shift"),
        //ffi::VK_CONTROL => Some("Control"),
        //ffi::VK_MENU => Some("Menu"),
        ffi::VK_PAUSE => Some("Pause"),
        ffi::VK_CAPITAL => Some("Capital"),
        ffi::VK_KANA => Some("Kana"),
        //ffi::VK_HANGUEL => Some("Hanguel"),
        //ffi::VK_HANGUL => Some("Hangul"),
        //ffi::VK_JUNJA => Some("Junja"),
        //ffi::VK_FINAL => Some("Final"),
        //ffi::VK_HANJA => Some("Hanja"),
        ffi::VK_KANJI => Some("Kanji"),
        ffi::VK_ESCAPE => Some("Escape"),
        ffi::VK_CONVERT => Some("Convert"),
        //ffi::VK_NONCONVERT => Some("Nonconvert"),
        //ffi::VK_ACCEPT => Some("Accept"),
        //ffi::VK_MODECHANGE => Some("Modechange"),
        ffi::VK_SPACE => Some("Space"),
        ffi::VK_PRIOR => Some("PageUp"),
        ffi::VK_NEXT => Some("PageDown"),
        ffi::VK_END => Some("End"),
        ffi::VK_HOME => Some("Home"),
        ffi::VK_LEFT => Some("Left"),
        ffi::VK_UP => Some("Up"),
        ffi::VK_RIGHT => Some("Right"),
        ffi::VK_DOWN => Some("Down"),
        //ffi::VK_SELECT => Some("Select"),
        //ffi::VK_PRINT => Some("Print"),
        //ffi::VK_EXECUTE => Some("Execute"),
        ffi::VK_SNAPSHOT => Some("Snapshot"),
        ffi::VK_INSERT => Some("Insert"),
        ffi::VK_DELETE => Some("Delete"),
        //ffi::VK_HELP => Some("Help"),
        0x30 => Some("Key0"),
        0x31 => Some("Key1"),
        0x32 => Some("Key2"),
        0x33 => Some("Key3"),
        0x34 => Some("Key4"),
        0x35 => Some("Key5"),
        0x36 => Some("Key6"),
        0x37 => Some("Key7"),
        0x38 => Some("Key8"),
        0x39 => Some("Key9"),
        0x41 => Some("A"),
        0x42 => Some("B"),
        0x43 => Some("C"),
        0x44 => Some("D"),
        0x45 => Some("E"),
        0x46 => Some("F"),
        0x47 => Some("G"),
        0x48 => Some("H"),
        0x49 => Some("I"),
        0x4A => Some("J"),
        0x4B => Some("K"),
        0x4C => Some("L"),
        0x4D => Some("M"),
        0x4E => Some("N"),
        0x4F => Some("O"),
        0x50 => Some("P"),
        0x51 => Some("Q"),
        0x52 => Some("R"),
        0x53 => Some("S"),
        0x54 => Some("T"),
        0x55 => Some("U"),
        0x56 => Some("V"),
        0x57 => Some("W"),
        0x58 => Some("X"),
        0x59 => Some("Y"),
        0x5A => Some("Z"),
        //ffi::VK_LWIN => Some("Lwin"),
        //ffi::VK_RWIN => Some("Rwin"),
        ffi::VK_APPS => Some("ContextMenu"),
        ffi::VK_SLEEP => Some("StandBy"),
        ffi::VK_NUMPAD0 => Some("Numpad0"),
        ffi::VK_NUMPAD1 => Some("Numpad1"),
        ffi::VK_NUMPAD2 => Some("Numpad2"),
        ffi::VK_NUMPAD3 => Some("Numpad3"),
        ffi::VK_NUMPAD4 => Some("Numpad4"),
        ffi::VK_NUMPAD5 => Some("Numpad5"),
        ffi::VK_NUMPAD6 => Some("Numpad6"),
        ffi::VK_NUMPAD7 => Some("Numpad7"),
        ffi::VK_NUMPAD8 => Some("Numpad8"),
        ffi::VK_NUMPAD9 => Some("Numpad9"),
        ffi::VK_MULTIPLY => Some("Multiply"),
        ffi::VK_ADD => Some("Add"),
        //ffi::VK_SEPARATOR => Some("Separator"),
        ffi::VK_SUBTRACT => Some("Subtract"),
        ffi::VK_DECIMAL => Some("Decimal"),
        ffi::VK_DIVIDE => Some("Divide"),
        ffi::VK_F1 => Some("F1"),
        ffi::VK_F2 => Some("F2"),
        ffi::VK_F3 => Some("F3"),
        ffi::VK_F4 => Some("F4"),
        ffi::VK_F5 => Some("F5"),
        ffi::VK_F6 => Some("F6"),
        ffi::VK_F7 => Some("F7"),
        ffi::VK_F8 => Some("F8"),
        ffi::VK_F9 => Some("F9"),
        ffi::VK_F10 => Some("F10"),
        ffi::VK_F11 => Some("F11"),
        ffi::VK_F12 => Some("F12"),
        ffi::VK_F13 => Some("F13"),
        ffi::VK_F14 => Some("F14"),
        ffi::VK_F15 => Some("F15"),
        /*ffi::VK_F16 => Some("F16"),
        ffi::VK_F17 => Some("F17"),
        ffi::VK_F18 => Some("F18"),
        ffi::VK_F19 => Some("F19"),
        ffi::VK_F20 => Some("F20"),
        ffi::VK_F21 => Some("F21"),
        ffi::VK_F22 => Some("F22"),
        ffi::VK_F23 => Some("F23"),
        ffi::VK_F24 => Some("F24"),*/
        ffi::VK_NUMLOCK => Some("NumLock"),
        ffi::VK_SCROLL => Some("Scroll"),
        /*ffi::VK_LSHIFT => Some("Lshift"),
        ffi::VK_RSHIFT => Some("Rshift"),
        ffi::VK_LCONTROL => Some("Lcontrol"),
        ffi::VK_RCONTROL => Some("Rcontrol"),
        ffi::VK_LMENU => Some("Lmenu"),
        ffi::VK_RMENU => Some("Rmenu"),
        ffi::VK_BROWSER_BACK => Some("Browser_back"),
        ffi::VK_BROWSER_FORWARD => Some("Browser_forward"),
        ffi::VK_BROWSER_REFRESH => Some("Browser_refresh"),
        ffi::VK_BROWSER_STOP => Some("Browser_stop"),
        ffi::VK_BROWSER_SEARCH => Some("Browser_search"),
        ffi::VK_BROWSER_FAVORITES => Some("Browser_favorites"),
        ffi::VK_BROWSER_HOME => Some("Browser_home"),
        ffi::VK_VOLUME_MUTE => Some("Volume_mute"),
        ffi::VK_VOLUME_DOWN => Some("Volume_down"),
        ffi::VK_VOLUME_UP => Some("Volume_up"),
        ffi::VK_MEDIA_NEXT_TRACK => Some("Media_next_track"),
        ffi::VK_MEDIA_PREV_TRACK => Some("Media_prev_track"),
        ffi::VK_MEDIA_STOP => Some("Media_stop"),
        ffi::VK_MEDIA_PLAY_PAUSE => Some("Media_play_pause"),
        ffi::VK_LAUNCH_MAIL => Some("Launch_mail"),
        ffi::VK_LAUNCH_MEDIA_SELECT => Some("Launch_media_select"),
        ffi::VK_LAUNCH_APP1 => Some("Launch_app1"),
        ffi::VK_LAUNCH_APP2 => Some("Launch_app2"),
        ffi::VK_OEM_1 => Some("Oem_1"),
        ffi::VK_OEM_PLUS => Some("Oem_plus"),
        ffi::VK_OEM_COMMA => Some("Oem_comma"),
        ffi::VK_OEM_MINUS => Some("Oem_minus"),
        ffi::VK_OEM_PERIOD => Some("Oem_period"),
        ffi::VK_OEM_2 => Some("Oem_2"),
        ffi::VK_OEM_3 => Some("Oem_3"),
        ffi::VK_OEM_4 => Some("Oem_4"),
        ffi::VK_OEM_5 => Some("Oem_5"),
        ffi::VK_OEM_6 => Some("Oem_6"),
        ffi::VK_OEM_7 => Some("Oem_7"),
        ffi::VK_OEM_8 => Some("Oem_8"),
        ffi::VK_OEM_102 => Some("Oem_102"),
        ffi::VK_PROCESSKEY => Some("Processkey"),
        ffi::VK_PACKET => Some("Packet"),
        ffi::VK_ATTN => Some("Attn"),
        ffi::VK_CRSEL => Some("Crsel"),
        ffi::VK_EXSEL => Some("Exsel"),
        ffi::VK_EREOF => Some("Ereof"),
        ffi::VK_PLAY => Some("Play"),
        ffi::VK_ZOOM => Some("Zoom"),
        ffi::VK_NONAME => Some("Noname"),
        ffi::VK_PA1 => Some("Pa1"),
        ffi::VK_OEM_CLEAR => Some("Oem_clear"),*/
        _ => return None
    }
}
